In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

file_path = '/content/drive/MyDrive/MachineLearningRating_v3.csv'
df = pd.read_csv(file_path, delimiter='|')  # Use '|' as delimiter
df.info()
df.describe()

<ipython-input-4-fef2fc7be864>:4: DtypeWarning: Columns (0,3,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, delimiter='|')  # Use '|' as delimiter

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  object
 1   PolicyID                  973382 non-null   float64
 2   TransactionMonth          973382 non-null   object
 3   IsVATRegistered           973382 non-null   object
 4   Citizenship               973382 non-null   object
 5   LegalType                 973382 non-null   object
 6   Title                     973382 non-null   object
 7   Language                  973382 non-null   object
 8   Bank                      831862 non-null   object
 9   AccountType               934647 non-null   object
 10  MaritalStatus             965123 non-null   object
 11  Gender                    963846 non-null   object
 12  Country                   973382 non-null   object
 13  Province                  973382 non-null   object
 14  PostalCode                973382 non-null   float64
 15  MainCrestaZone            973382 non-null   object
 16  SubCrestaZone             973382 non-null   object
 17  ItemType                  973382 non-null   object
 18  mmcode                    972830 non-null   float64
 19  VehicleType               972830 non-null   object
 20  RegistrationYear          973382 non-null   float64
 21  make                      972830 non-null   object
 22  Model                     972830 non-null   object
 23  Cylinders                 972830 non-null   float64
 24  cubiccapacity             972830 non-null   float64
 25  kilowatts                 972830 non-null   float64
 26  bodytype                  972830 non-null   object
 27  NumberOfDoors             972830 non-null   float64
 28  VehicleIntroDate          972830 non-null   object
 29  CustomValueEstimate       214663 non-null   float64
 30  AlarmImmobiliser          973382 non-null   object
 31  TrackingDevice            973382 non-null   object
 32  CapitalOutstanding        973380 non-null   float64
 33  NewVehicle                820829 non-null   object
 34  WrittenOff                349116 non-null   object
 35  Rebuilt                   349116 non-null   object
 36  Converted                 349116 non-null   object
 37  CrossBorder               698 non-null      object
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                973382 non-null   float64
 40  TermFrequency             973382 non-null   object
 41  CalculatedPremiumPerTerm  973382 non-null   float64
 42  ExcessSelected            973382 non-null   object
 43  CoverCategory             973382 non-null   object
 44  CoverType                 973382 non-null   object
 45  CoverGroup                973382 non-null   object
 46  Section                   973382 non-null   object
 47  Product                   973382 non-null   object
 48  StatutoryClass            973382 non-null   object
 49  StatutoryRiskType         973382 non-null   object
 50  TotalPremium              973382 non-null   float64
 51  TotalClaims               973382 non-null   float64
dtypes: float64(15), object(37)
memory usage: 396.8+ MB

,PolicyID,PostalCode,mmcode,RegistrationYear,Cylinders,cubiccapacity,kilowatts,NumberOfDoors,CustomValueEstimate,CapitalOutstanding,NumberOfVehiclesInFleet,SumInsured,CalculatedPremiumPerTerm,TotalPremium,TotalClaims
count,973382.000000,973382.000000,9.728300e+05,973382.000000,972830.000000,972830.000000,972830.000000,972830.000000,2.146630e+05,973380.000000,0.0,9.733820e+05,973382.000000,973382.000000,973382.000000
mean,7891.596664,2948.950155,5.479908e+07,2010.189761,4.047416,2467.546929,97.316719,4.016624,2.244353e+05,52346.863964,NaN,6.049110e+05,117.516479,61.737566,65.583857
std,5292.157633,2646.084789,1.370179e+07,3.261043,0.296717,443.962832,19.410540,0.469113,5.718529e+05,110952.357094,NaN,1.509810e+06,403.230631,231.722484,2390.027959
min,14.000000,1.000000,4.041200e+06,1987.000000,0.000000,0.000000,0.000000,0.000000,2.000000e+04,-2.000000,NaN,1.000000e-02,0.000000,-782.576754,-12002.412281
25%,4414.000000,700.000000,6.005692e+07,2008.000000,4.000000,2237.000000,75.000000,4.000000,1.350000e+05,0.000000,NaN,5.000000e+03,3.197500,0.000000,0.000000
50%,7033.000000,2000.000000,6.005842e+07,2011.000000,4.000000,2694.000000,111.000000,4.000000,2.200000e+05,0.000000,NaN,7.500000e+03,8.401250,2.175614,0.000000
75%,11008.000000,4093.000000,6.005842e+07,2013.000000,4.000000,2694.000000,111.000000,4.000000,2.800000e+05,0.000000,NaN,2.500000e+05,90.000000,21.929825,0.000000
max,23246.000000,9870.000000,6.506535e+07,2015.000000,10.000000,12880.000000,309.000000,6.000000,2.655000e+07,700000.000000,NaN,1.263620e+07,74422.167900,65282.603421,393092.105263

In [5]:
print(df.columns)

Index(['UnderwrittenCoverID', 'PolicyID', 'TransactionMonth',
       'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language',
       'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province',
       'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'mmcode',
       'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders',
       'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors',
       'VehicleIntroDate', 'CustomValueEstimate', 'AlarmImmobiliser',
       'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff',
       'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet',
       'SumInsured', 'TermFrequency', 'CalculatedPremiumPerTerm',
       'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section',
       'Product', 'StatutoryClass', 'StatutoryRiskType', 'TotalPremium',
       'TotalClaims'],
      dtype='object')

In [26]:
# Select only numeric columns
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Fill missing values in numeric columns with the median of each column
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [27]:
# Select non-numeric columns
non_numeric_cols = df.select_dtypes(exclude=['float64', 'int64']).columns

# Fill missing values in non-numeric columns with the mode of each column
for col in non_numeric_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

<ipython-input-27-150a5af3363a>:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].mode()[0])

In [29]:
df = pd.get_dummies(df, columns=['Province', 'Gender', 'PostalCode'], drop_first=True)

In [31]:
df['ProfitMargin'] = df['TotalPremium'] - df['TotalClaims']

In [33]:
X = df.drop(columns=['TotalClaims'])  # Features
y = df['TotalClaims']  # Target

In [ ]:
!pip install pandas
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Assuming 'MachineLearningRating_v3.csv' is in the current directory or adjust the path accordingly
file_path = 'MachineLearningRating_v3.csv'
df = pd.read_csv(file_path, delimiter='|')  # Load the dataframe

# ... (Rest of the data preprocessing code as provided earlier) ...

# Select only numeric columns
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Fill missing values in numeric columns with the median of each column
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# Select non-numeric columns
non_numeric_cols = df.select_dtypes(exclude=['float64', 'int64']).columns

# Fill missing values in non-numeric columns with the mode of each column
for col in non_numeric_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df = pd.get_dummies(df, columns=['Province', 'Gender', 'PostalCode'], drop_first=True)

df['ProfitMargin'] = df['TotalPremium'] - df['TotalClaims']

# Split the data into features and target
X = df.drop(columns=['TotalClaims'])  # Features
y = df['TotalClaims']  # Target

In [ ]:
!pip install pandas scikit-learn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from google.colab import drive
drive.mount('/content/drive')
# Assuming 'MachineLearningRating_v3.csv' is in the current directory or adjust the path accordingly
import pandas as pd

file_path = '/content/drive/MyDrive/MachineLearningRating_v3.csv'
# ... (Rest of the data preprocessing code as provided earlier) ...
import pandas as pd

file_path = '/content/drive/MyDrive/MachineLearningRating_v3.csv'
df = pd.read_csv(file_path, delimiter='|')  # Use '|' as delimiter
df.info()
df.describe()

# Select only numeric columns
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Fill missing values in numeric columns with the median of each column
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# Select non-numeric columns
non_numeric_cols = df.select_dtypes(exclude=['float64', 'int64']).columns

# Fill missing values in non-numeric columns with the mode of each column
for col in non_numeric_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df = pd.get_dummies(df, columns=['Province', 'Gender', 'PostalCode'], drop_first=True)

df['ProfitMargin'] = df['TotalPremium'] - df

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.6.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<ipython-input-14-d0dda5f5e3c4>:16: DtypeWarning: Columns (0,3,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, delimiter='|')  # Use '|' as delimiter

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  object
 1   PolicyID                  973382 non-null   float64
 2   TransactionMonth          973382 non-null   object
 3   IsVATRegistered           973382 non-null   object
 4   Citizenship               973382 non-null   object
 5   LegalType                 973382 non-null   object
 6   Title                     973382 non-null   object
 7   Language                  973382 non-null   object
 8   Bank                      831862 non-null   object
 9   AccountType               934647 non-null   object
 10  MaritalStatus             965123 non-null   object
 11  Gender                    963846 non-null   object
 12  Country                   973382 non-null   object
 13  Province                  973382 non-null   object
 14  PostalCode                973382 non-null   float64
 15  MainCrestaZone            973382 non-null   object
 16  SubCrestaZone             973382 non-null   object
 17  ItemType                  973382 non-null   object
 18  mmcode                    972830 non-null   float64
 19  VehicleType               972830 non-null   object
 20  RegistrationYear          973382 non-null   float64
 21  make                      972830 non-null   object
 22  Model                     972830 non-null   object
 23  Cylinders                 972830 non-null   float64
 24  cubiccapacity             972830 non-null   float64
 25  kilowatts                 972830 non-null   float64
 26  bodytype                  972830 non-null   object
 27  NumberOfDoors             972830 non-null   float64
 28  VehicleIntroDate          972830 non-null   object
 29  CustomValueEstimate       214663 non-null   float64
 30  AlarmImmobiliser          973382 non-null   object
 31  TrackingDevice            973382 non-null   object
 32  CapitalOutstanding        973380 non-null   float64
 33  NewVehicle                820829 non-null   object
 34  WrittenOff                349116 non-null   object
 35  Rebuilt                   349116 non-null   object
 36  Converted                 349116 non-null   object
 37  CrossBorder               698 non-null      object
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                973382 non-null   float64
 40  TermFrequency             973382 non-null   object
 41  CalculatedPremiumPerTerm  973382 non-null   float64
 42  ExcessSelected            973382 non-null   object
 43  CoverCategory             973382 non-null   object
 44  CoverType                 973382 non-null   object
 45  CoverGroup                973382 non-null   object
 46  Section                   973382 non-null   object
 47  Product                   973382 non-null   object
 48  StatutoryClass            973382 non-null   object
 49  StatutoryRiskType         973382 non-null   object
 50  TotalPremium              973382 non-null   float64
 51  TotalClaims               973382 non-null   float64
dtypes: float64(15), object(37)
memory usage: 396.8+ MB

<ipython-input-14-d0dda5f5e3c4>:31: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].mode()[0])

In [1]:
import shap

explainer = shap.Explainer(xgb_model)
shap_values = explainer(X_test)

shap.summary_plot(shap_values, X_test)

NameError: name 'xgb_model' is not defined